version: '3'
services:
    postgres:
        image: postgres:12.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: qwe123
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    back:
        build:
            context: ./back
            dockerfile: Dockerfile
        volumes:
            - ./back/src:/app/src
            - ./back/tests:/app/tests
        ports:
            - "3333:3333"
        entrypoint: yarn
        command: start
    # front:
    #     build:
    #         context: ./front
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ./front:/app
    #     ports:
    #         - "3000:3000"
    #         - "35729:35729"
    #     entrypoint: yarn
    #     command: start